apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Valeurs encodées en base64
  # 'admin' -> YWRtaW4=
  # 'password123' -> cGFzc3dvcmQxMjM=
  DB_USER: YWRtaW4=
  DB_PASSWORD: GFzc3dvcmQxMjMc=