apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-api
  namespace: default # On s'assure d'être dans le même namespace que la Gateway
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: mon-app-container
        image: mon-app-k8s:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets-api # Ajusté selon le nom vu dans tes logs d'erreur ArgoCD
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets-api # Ajusté selon le nom vu dans tes logs d'erreur ArgoCD
              key: DB_PASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: app-config # Doit correspondre au metadata.name du configmap de ton dossier /api
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-api-service # <-- TRÈS IMPORTANT : Doit correspondre EXACTEMENT au backendRefs de ta gateway
  namespace: default
spec:
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # <-- CHANGÉ : C'est la Gateway qui gère l'exposition, pas besoin de LoadBalancer ici !